build:
  version: "3.0"

accounts:
  message: "Welcome to eazybank account related local APIs"
  contactDetails:
    name: "Rahul Vijay - Developer"
    email: "frederickraghul@gmail.com"
  onCallSupport:
      -(555)555-1234
      -(555)555-1345