build:
  version: "2.0"

accounts:
  message: "Welcome to eazybank account related QA APIs"
  contactDetails:
    name: "Praveen Kumar - Developer"
    email: "supraveensrt@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-1345