build:
  version: "1.0"

cards:
  message: "Welcome to eazybank cards related Prod APIs"
  contactDetails:
    name: "James - Developer"
    email: "james@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-1345