build:
  version: "1.0"

cards:
  message: "Welcome to eazybank cards related local APIs"
  contactDetails:
    name: "Rahul Vijay - Developer"
    email: "frederickraghul@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-1345