build:
  version: "2.0"

loans:
  message: "Welcome to eazybank loans related QA APIs"
  contactDetails:
    name: "Parveen Kumar - Developer"
    email: "supraveensrt@gmail.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-1345